name: Build cppdap
description: builds the cppdap project
inputs:
  msan:
    description: 'Enable Memory Sanitizer'
    required: false
    default: false
  tsan:
    description: 'Enable Thread Sanitizer'
    required: false
    default: false
  asan:
    description: 'Enable Address Sanitizer'
    required: false
    default: false
  config:
    description: 'Build configuration'
    required: false
    default: "Debug"
  tests:
    description: 'Build tests'
    required: false
    default: false
  fuzzer:
    description: 'Build fuzzer'
    required: false
    default: false
  CXX:
    description: 'C++ Compiler to use'
    required: false
    default: ''
  CC:
    description: 'C Compiler to use'
    required: false
    default: ''
  install:
    description: 'Install the build'
    required: false
    default: false
  install_prefix:
    description: 'Install prefix'
    required: false
    default: 'out/usr/local'

runs:
  using: "composite"
  steps:
    - name: Build source
      shell: bash
      run: |
        mkdir -p build
        cd build
        CC="${{ inputs.CC }}" CXX="${{ inputs.CXX }}" cmake .. -DCPPDAP_BUILD_TESTS=${{ inputs.tests }} -DCPPDAP_BUILD_FUZZER=${{ inputs.fuzzer }} -DCPPDAP_MSAN=${{ inputs.msan }} -DCPPDAP_TSAN=${{ inputs.tsan }} -DCPPDAP_ASAN=${{ inputs.asan }} -DCMAKE_BUILD_TYPE=${{ inputs.config }}
        cmake --build . --config ${{ inputs.config }}
    - name: Install
      shell: bash
      if: inputs.install == 'true'
      run: |
        cmake --install ./build --config ${{ inputs.config }} --prefix ${{ inputs.install_prefix }}